name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --immutable
      - name: Build
        run: yarn build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: omardiab
          entrypoint: ./dist/server/entry.mjs
